### ISSUE TITLE
No such command exists

### ISSUE THREAD

**Issue by sivert-io** [BillyGalbreath/VS-LiveMap#1]
Hi! 👋🏼 

I am using your latest dev build, livemap-0.0.7-b159, and receive this error _No such command exists_ when running `.livemap colormap` as an admin in-game.

**Comment by sivert-io** [comment]
I assume this means I need to install the mod client-side... Was expecting this to be a server-side only mod as it is listed as 

> Side: Server

on the modpage 🤔

**Comment by sivert-io** [comment]
Would suggest adding to the mod-page what you've written in the wiki 😃 

> Install the mod on your client in order to run the [.livemap colormap](https://github.com/BillyGalbreath/VS-LiveMap/wiki/Commands#colormap) client command to generate a [colormap](https://github.com/BillyGalbreath/VS-LiveMap/wiki/Colormap-Yml).

**Comment by sivert-io** [comment]
After installing locally the issue still persists.

**Comment by BillyGalbreath** [comment]
The commands are only temporary solution while I work on something easier to use.

The latest dev builds no longer contain that command, and the new installation instructions have not been documented yet.
